# Generated by Django 4.2.7 on 2023-11-07 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.TextField(max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stock', models.IntegerField(default=0)),
                ('brand', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('activity', 'Activity'), ('business and finance', 'Business And Finance'), ('educational resources', 'Educational Resources'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('home improvement', 'Home Improvement'), ('industry news', 'Industry News'), ('lifestyle', 'Lifestyle'), ('news', 'News'), ('politics', 'Politics'), ('religion', 'Religion'), ('science', 'Science'), ('sports', 'Sports'), ('technology', 'Technology'), ('travel', 'Travel'), ('world', 'World')], max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
